# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3"
services:

  selenium-hub:
    image: selenium/hub:3.12.0-cobalt
    container_name: selenium-hub
    ports:
      - "4444:4444"

  redis:
    image: redis:3.2.11
    container_name: redis
    ports:
      - "6379"

  chrome:
    image: selenium/node-chrome:3.12.0-cobalt
    volumes:
      - /dev/shm:/dev/shm
    container_name: chrome
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  messenger:
    build: .
    image: messenger
    container_name: messenger
    command: gunicorn --config gunicorn.conf api:app
    ports:
      - "8000:8000"
    env_file:
      - .docker.env

  worker:
    image: messenger
    container_name: worker
    command: python worker.py
    env_file:
      - .docker.env
